### ISSUE TITLE
Issue translating Sigma Correlation Rules

### ISSUE THREAD

**Issue by 0xpermafrost** [SigmaHQ/pySigma-backend-opensearch#2]
First, many thanks for this great project!

I tried to transform a Sigma Correlation Rule to Opensearch. To achieve this,  I have written a rule (see below) and tried to convert it into opensearch alert rules using your tool but sadly had no success. I tried the following rule:

```
title: Okta MFA bruteforce
id: be815121-8efb-4a71-8718-c61ad9a71ee9
status: experimental
description: Detects a Okta MFA Bruteforce attempts
references: https://developer.okta.com/docs/reference/api/event-types/
author: 0xpermaFrost
date: 2024/02/21
correlation:
    type: event_count
    rules:
	- failed_login
    group-by:
	- actor.alternateId
    timespan: 15m
    condition:
	gte: 15
falsepositives:
    - Script uses an outdated user authentication
---
title: Okta failed MFA Login
id: a17da3d5-6481-4ae7-ad15-e672be9f180d
name: failed_login
logsource:
    product: okta
    service: okta
detection:
    selection:
	eventtype: 'user.authentication.auth_via_mfa'
	outcome.result: 'FAILURE'
    condition: selection
level: medium
```

When trying the conversion using the flag "-f monitor_rule", I get a python error.

```
Traceback (most recent call last):
  File "/home/user/sigma-cli/bin/sigma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/sigma/cli/main.py", line 55, in main
    cli()
  File "/home/user/sigma-cli/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/sigma/cli/convert.py", line 260, in convert
    result = backend.convert(rule_collection, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/sigma/conversion/base.py", line 135, in convert
    queries = [
              ^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/sigma/conversion/base.py", line 138, in <listcomp>
    for query in self.convert_rule(rule, output_format or self.default_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sigma-cli/lib/python3.11/site-packages/sigma/conversion/base.py", line 160, in convert_rule
    for _ in rule.detection.parsed_condition
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parsed_condition' 
```

If I convert it without the flag, I get the following result, which doesn't work in opensearch.
`(eventtype:user.authentication.auth_via_mfa AND data.aws.outcome.result:FAILURE) AND ""count\(data.aws.actor.alternateId\)\ \>\ 10""`

Can you please check what I am doing wrong? 

Many thanks and keep up the good work 🙂

**Comment by thomaspatzke** [comment]
It's not supported by the backend yet. A first version of a new ES|QL backend with correlation support will be reelased soon.
